ALTER TABLE "_PREFIX_curstats"
	ADD COLUMN "blessing" TINYINT NOT NULL DEFAULT 1;

ALTER TABLE "_PREFIX_experience"
	ADD COLUMN "blessing" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "_PREFIX_maxstats"
	ADD COLUMN "blessing" TINYINT NOT NULL DEFAULT 1;

ALTER TABLE "_PREFIX_capped_experience"
	ADD COLUMN "blessing" INTEGER;
