ALTER TABLE "_PREFIX_curstats"
	ADD COLUMN "summoning" TINYINT NOT NULL DEFAULT 1;

ALTER TABLE "_PREFIX_experience"
	ADD COLUMN "summoning" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "_PREFIX_maxstats"
	ADD COLUMN "summoning" TINYINT NOT NULL DEFAULT 1;

ALTER TABLE "_PREFIX_capped_experience"
	ADD COLUMN "summoning" INTEGER;
