#!/usr/bin/env python3
"""Generate paired client/server held-family catalogs; never modify gameplay data."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = json.loads((ROOT / 'tools/generators/held-equipment-families.json').read_text())
    definitions, mappings = data['definitions'], data['mappings']
    assert [x['appearanceId'] for x in definitions] == list(range(1130, 1130 + len(definitions)))
    assert len({x['itemId'] for x in mappings}) == len(mappings)
    body = '''// Generated by tools/generators/generate-held-equipment-families.py. Do not edit.
package PACKAGE;

public final class HeldEquipmentFamilies {
    private HeldEquipmentFamilies() { }
    public static final int FIRST_APPEARANCE_ID = 1130;
    public static final class Definition {
        public final int appearanceId, mask;
        public final String family;
        private Definition(int id, String family, int mask) {
            this.appearanceId = id; this.family = family; this.mask = mask;
        }
    }
    public static final class Mapping {
        public final int itemId, appearanceId, fallbackAppearance;
        private Mapping(int item, int appearance, int fallback) {
            itemId = item; appearanceId = appearance; fallbackAppearance = fallback;
        }
    }
    public static final java.util.List<Definition> DEFINITIONS = java.util.Collections.unmodifiableList(java.util.Arrays.asList(
DEFINITIONS
    ));
    public static final java.util.List<Mapping> MAPPINGS = java.util.Collections.unmodifiableList(java.util.Arrays.asList(
MAPPINGS
    ));
}
'''
    body = body.replace('DEFINITIONS\n', ',\n'.join(
        f'        new Definition({x["appearanceId"]}, "{x["family"]}", 0x{x["mask"]:06x})' for x in definitions) + '\n')
    body = body.replace('MAPPINGS\n', ',\n'.join(
        f'        new Mapping({x["itemId"]}, {x["appearanceId"]}, {x["fallbackAppearance"]})' for x in mappings) + '\n')
    for package, source in [
        ('com.openrsc.server.external', 'server/src/com/openrsc/server/external'),
        ('com.openrsc.client.entityhandling', 'Client_Base/src/com/openrsc/client/entityhandling'),
    ]:
        target = ROOT / source / 'HeldEquipmentFamilies.java'
        content = body.replace('PACKAGE', package)
        if args.check:
            assert target.read_text() == content, f'Stale generated catalog: {target}'
        else:
            target.write_text(content)
    print('PASS: paired held-family catalogs' + (' are current' if args.check else ' generated'))


if __name__ == '__main__':
    main()
